select * from sys.symmetric_keys
select * from sys.asymmetric_keys
select * from sys.certificates
select * from sys.openkeys
select * from sys.key_encryptions
select * from sys.column_encryption_keys
select * from sys.column_encryption_key_values
select * from sys.security_policies
select * from sys.security_predicates